before_install:
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
  - "sudo apt-get install graphviz 2>&1 | tail -n 2"
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/plantuml.jar
  - hg clone -r 8.6.7 https://asciidoc.googlecode.com/hg/ asciidoc-8.6.7
before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.3.tar.gz -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.0.3/bin/
language: java
script:
  - java -version
  - javac -version
  - python -V
  - phantomjs -v
  - python asciidoc-8.6.7/asciidoc.py --version
  - dot -V
  - casperjs --version
  - echo Hello from DUT INFO Blagnac
  - ls -alF
  - cd sprint_5
  - echo Java Compilation
  - javac -cp .:OPTI/bin/data -d OPTI/bin OPTI/src/data/*.java
  - javac -cp .:OPTI/bin/gui -d OPTI/bin OPTI/src/gui/*.java
  - javac -cp .:OPTI/bin/lib -d OPTI/bin OPTI/src/lib/*.java
  - echo Launching Java tests
  - java -cp .;junit.jar OPTI/bin/lib/OptiParserTest
  - echo Documentations generatrion
  - python ../asciidoc-8.6.7/asciidoc.py -b slidy -a data-uri -o srcdoc/presentationFinale.html srcdoc/presentationFinale.txt
  - ls -alF srcdoc
  - cd bin
  - java -cp .:../../junit.jar HelloMondeTest
  - cd ../OPTIweb/test
  - cp OPTIwebprof.html /tmp/OPTIweb.html
  - casperjs test casperAccueil.js